package com.mycompany.nomina;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Frontend extends javax.swing.JFrame {

    boolean EditModeEnable = false;
    int SelectedID = 0;
    
    public Frontend() {
        initComponents();
    }
    
    public void ResetTable() {
        DefaultTableModel table = (DefaultTableModel) E_table.getModel();
        int count = table.getRowCount();
        while (count > 0) {
            table.removeRow(count - 1);
            count = table.getRowCount();
        }
    }
    
    public void ReloadTable(){
        Enumeration<Integer> e = Backend.GetEmployeeList().keys();
        DefaultTableModel table = (DefaultTableModel) E_table.getModel();
        while(e.hasMoreElements()){
            int key = e.nextElement();
            Object[] rowData = {Backend.GetEmployee(key).GetID(), 
                                Backend.GetEmployee(key).GetCedula(),
                                Backend.GetEmployee(key).GetName(),
                                Backend.GetEmployee(key).GetLastname(),
                                Backend.GetEmployee(key).GetSalary(),
                                Backend.GetEmployee(key).CalcAfp(),
                                Backend.GetEmployee(key).CalcArs(),
                                Backend.GetEmployee(key).CalcIsr(),
                                Backend.GetEmployee(key).CalcSueldoNeto(),
                                Backend.GetEmployee(key).GetMaritalStatus(),
                                Backend.GetEmployee(key).GetStatus()}; 
            table.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        E_Name = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        E_Lastname = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        E_Cedula = new javax.swing.JTextField();
        E_MaritalStatus = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        E_Salary = new javax.swing.JTextField();
        javax.swing.JButton Btn_Confirm = new javax.swing.JButton();
        javax.swing.JButton Btn_Cancel = new javax.swing.JButton();
        javax.swing.JLabel Label_status = new javax.swing.JLabel();
        E_Status = new javax.swing.JComboBox<>();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        E_table = new javax.swing.JTable();
        E_Find = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nomina de empleados:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");

        E_Name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        E_Lastname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Cedula");

        E_Cedula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        E_MaritalStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        E_MaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Union Libre" }));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Estado civil");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("Salario");

        E_Salary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Btn_Confirm.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Btn_Confirm.setText("Confirmar");
        Btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmActionPerformed(evt);
            }
        });

        Btn_Cancel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Btn_Cancel.setText("Cancelar");
        Btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelActionPerformed(evt);
            }
        });

        Label_status.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Label_status.setText("Estado del empleado");

        E_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(E_Salary, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(E_MaritalStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E_Name)
                    .addComponent(E_Lastname)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E_Cedula)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Btn_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(Btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addComponent(Label_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(E_Status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(E_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E_MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        E_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cedula", "Nombre", "Apellido", "Salario bruto", "AFP", "ARS", "ISR", "Sueldo Neto", "Estado Civil", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        E_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(E_table);
        if (E_table.getColumnModel().getColumnCount() > 0) {
            E_table.getColumnModel().getColumn(2).setMinWidth(140);
            E_table.getColumnModel().getColumn(2).setMaxWidth(140);
            E_table.getColumnModel().getColumn(3).setMinWidth(140);
            E_table.getColumnModel().getColumn(3).setMaxWidth(140);
        }

        E_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                E_FindKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("Filtrar:");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel8.setText("Reporte:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(E_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName("Buscar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmActionPerformed
        String name = E_Name.getText();
        String lastname = E_Lastname.getText();
        String marital_status = E_MaritalStatus.getSelectedItem().toString();
        String status = E_Status.getSelectedItem().toString();
        String cedula = E_Cedula.getText();
        String s_salary = E_Salary.getText();
        
        if (name.isEmpty() || lastname.isEmpty() || marital_status.isEmpty() || cedula.isEmpty() || s_salary.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos porfavor", "Intenta de nuevo", ERROR_MESSAGE);
        } else {
            try {
                float salary = Float.parseFloat(s_salary);
                if(EditModeEnable){
                    try {
                        Connection conn = DriverManager.getConnection("jdbc:sqlite:database.db");
                        Backend.EditEmployee(conn,SelectedID, name, lastname, cedula, salary, marital_status, status);
                        conn.close();
                    } catch (SQLException e) {
                        e.printStackTrace();
                        System.out.println(e.getClass().getName() + ": " + e.getMessage());
                    }
                    EditModeEnable = false;
                    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18)));
                }else{
                    try {
                        Connection conn = DriverManager.getConnection("jdbc:sqlite:database.db");
                        Backend.AddEmployee(conn,name, lastname, cedula, salary, marital_status, status);
                        conn.close();
                    } catch (SQLException e) {
                        e.printStackTrace();
                        System.out.println(e.getClass().getName() + ": " + e.getMessage());
                    }
                }
                ResetTable();
                ReloadTable();
                JOptionPane.showMessageDialog(this, "Registrado correctamente", "Nomina Actualizada", INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Completa todos los campos correctamente", "Intenta de nuevo ", ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_Btn_ConfirmActionPerformed

    private void Btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelActionPerformed
        // TODO add your handling code here:
        E_Cedula.setText("");
        E_Lastname.setText("");
        E_Name.setText("");
        E_Salary.setText("");
        E_Status.setSelectedItem("INACTIVO");
        E_MaritalStatus.setSelectedItem("Soltero");
        EditModeEnable = false;
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18)));
    }//GEN-LAST:event_Btn_CancelActionPerformed

    private void E_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_E_FindKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) E_table.getModel();
        TableRowSorter<DefaultTableModel> table = new TableRowSorter<>(model);
        E_table.setRowSorter(table);
        table.setRowFilter(RowFilter.regexFilter(E_Find.getText()));
    }//GEN-LAST:event_E_FindKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ReloadTable();
    }//GEN-LAST:event_formWindowOpened

    private void E_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E_tableMouseClicked
        // TODO add your handling code here:
        int row = E_table.getSelectedRow();
        EditModeEnable = true;
        SelectedID = Integer.parseInt(E_table.getValueAt(row, 0).toString());
        E_Cedula.setText(E_table.getValueAt(row, 1).toString());
        E_Name.setText(E_table.getValueAt(row, 2).toString());
        E_Lastname.setText(E_table.getValueAt(row, 3).toString());
        E_Salary.setText(E_table.getValueAt(row, 4).toString());
        E_Status.setSelectedItem(E_table.getValueAt(row, 10).toString());
        E_MaritalStatus.setSelectedItem(E_table.getValueAt(row, 9).toString());
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Empleado ID: " + SelectedID, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 18))); // NOI18N
    }//GEN-LAST:event_E_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E_Cedula;
    private javax.swing.JTextField E_Find;
    private javax.swing.JTextField E_Lastname;
    private javax.swing.JComboBox<String> E_MaritalStatus;
    private javax.swing.JTextField E_Name;
    private javax.swing.JTextField E_Salary;
    private javax.swing.JComboBox<String> E_Status;
    private javax.swing.JTable E_table;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
